version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:15.7
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=sequelize_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    user: root
    volumes:
      - ./docker-data/data/postgres/data:/var/lib/postgresql/data
      - ./docker-data/data/postgres/config:/etc/postgresql

  postgres_setup:
    image: postgres:15.7
    user: root
    volumes:
      - ./docker-data/data/postgres/data:/var/lib/postgresql/data
      - ./docker-data/data/postgres/config:/etc/postgresql
    entrypoint: ['bash', '-c', 'chmod -R a+rwx /var/lib/postgresql/data && chmod -R a+rwx /etc/postgresql']
    depends_on:
      - postgres

  redis:
    container_name: redis
    image: redis:6-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./docker-data/data/redis:/data
    restart: unless-stopped

  backend:
    container_name: backend
    build:
      context: .
    restart: unless-stopped
    ports:
      - '4000:4000'
    env_file: .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./docker-data/data/media:/opt/app/storage/media
